formatted_link = '[{}]({})'
found = 'Bunu bulabildim:'
foundmuch = 'Bunları bulabildim:'
notfound = 'Bir şey bulamadım :('
resimyok = 'Bir şey bulamadım çünkü bu postta resim yok.'
sourcecode = '\r\n^[kaynak kodum](https://github.com/gHuseyinabi/RedditLinker)'